/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as MeRouteImport } from './routes/me'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as BankRouteImport } from './routes/bank'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileUserIdRouteImport } from './routes/profile.$userId'
import { Route as PackageIdRouteImport } from './routes/package.$id'
import { Route as AttemptIdRouteImport } from './routes/attempt.$id'
import { Route as PackageIdIndexRouteImport } from './routes/package.$id.index'
import { Route as PackageIdTakeRouteImport } from './routes/package.$id.take'
import { Route as PackageIdAttemptAttemptIdRouteImport } from './routes/package.$id.attempt.$attemptId'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const MeRoute = MeRouteImport.update({
  id: '/me',
  path: '/me',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const BankRoute = BankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const PackageIdRoute = PackageIdRouteImport.update({
  id: '/package/$id',
  path: '/package/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AttemptIdRoute = AttemptIdRouteImport.update({
  id: '/attempt/$id',
  path: '/attempt/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PackageIdIndexRoute = PackageIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PackageIdRoute,
} as any)
const PackageIdTakeRoute = PackageIdTakeRouteImport.update({
  id: '/take',
  path: '/take',
  getParentRoute: () => PackageIdRoute,
} as any)
const PackageIdAttemptAttemptIdRoute =
  PackageIdAttemptAttemptIdRouteImport.update({
    id: '/attempt/$attemptId',
    path: '/attempt/$attemptId',
    getParentRoute: () => PackageIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/bank': typeof BankRoute
  '/generate': typeof GenerateRoute
  '/history': typeof HistoryRoute
  '/jobs': typeof JobsRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/packages': typeof PackagesRoute
  '/settings': typeof SettingsRoute
  '/attempt/$id': typeof AttemptIdRoute
  '/package/$id': typeof PackageIdRouteWithChildren
  '/profile/$userId': typeof ProfileUserIdRoute
  '/package/$id/take': typeof PackageIdTakeRoute
  '/package/$id/': typeof PackageIdIndexRoute
  '/package/$id/attempt/$attemptId': typeof PackageIdAttemptAttemptIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/bank': typeof BankRoute
  '/generate': typeof GenerateRoute
  '/history': typeof HistoryRoute
  '/jobs': typeof JobsRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/packages': typeof PackagesRoute
  '/settings': typeof SettingsRoute
  '/attempt/$id': typeof AttemptIdRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/package/$id/take': typeof PackageIdTakeRoute
  '/package/$id': typeof PackageIdIndexRoute
  '/package/$id/attempt/$attemptId': typeof PackageIdAttemptAttemptIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/bank': typeof BankRoute
  '/generate': typeof GenerateRoute
  '/history': typeof HistoryRoute
  '/jobs': typeof JobsRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/me': typeof MeRoute
  '/packages': typeof PackagesRoute
  '/settings': typeof SettingsRoute
  '/attempt/$id': typeof AttemptIdRoute
  '/package/$id': typeof PackageIdRouteWithChildren
  '/profile/$userId': typeof ProfileUserIdRoute
  '/package/$id/take': typeof PackageIdTakeRoute
  '/package/$id/': typeof PackageIdIndexRoute
  '/package/$id/attempt/$attemptId': typeof PackageIdAttemptAttemptIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/bank'
    | '/generate'
    | '/history'
    | '/jobs'
    | '/landing'
    | '/login'
    | '/me'
    | '/packages'
    | '/settings'
    | '/attempt/$id'
    | '/package/$id'
    | '/profile/$userId'
    | '/package/$id/take'
    | '/package/$id/'
    | '/package/$id/attempt/$attemptId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/bank'
    | '/generate'
    | '/history'
    | '/jobs'
    | '/landing'
    | '/login'
    | '/me'
    | '/packages'
    | '/settings'
    | '/attempt/$id'
    | '/profile/$userId'
    | '/package/$id/take'
    | '/package/$id'
    | '/package/$id/attempt/$attemptId'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/bank'
    | '/generate'
    | '/history'
    | '/jobs'
    | '/landing'
    | '/login'
    | '/me'
    | '/packages'
    | '/settings'
    | '/attempt/$id'
    | '/package/$id'
    | '/profile/$userId'
    | '/package/$id/take'
    | '/package/$id/'
    | '/package/$id/attempt/$attemptId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BankRoute: typeof BankRoute
  GenerateRoute: typeof GenerateRoute
  HistoryRoute: typeof HistoryRoute
  JobsRoute: typeof JobsRoute
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  MeRoute: typeof MeRoute
  PackagesRoute: typeof PackagesRoute
  SettingsRoute: typeof SettingsRoute
  AttemptIdRoute: typeof AttemptIdRoute
  PackageIdRoute: typeof PackageIdRouteWithChildren
  ProfileUserIdRoute: typeof ProfileUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/me': {
      id: '/me'
      path: '/me'
      fullPath: '/me'
      preLoaderRoute: typeof MeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank': {
      id: '/bank'
      path: '/bank'
      fullPath: '/bank'
      preLoaderRoute: typeof BankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/package/$id': {
      id: '/package/$id'
      path: '/package/$id'
      fullPath: '/package/$id'
      preLoaderRoute: typeof PackageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attempt/$id': {
      id: '/attempt/$id'
      path: '/attempt/$id'
      fullPath: '/attempt/$id'
      preLoaderRoute: typeof AttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/package/$id/': {
      id: '/package/$id/'
      path: '/'
      fullPath: '/package/$id/'
      preLoaderRoute: typeof PackageIdIndexRouteImport
      parentRoute: typeof PackageIdRoute
    }
    '/package/$id/take': {
      id: '/package/$id/take'
      path: '/take'
      fullPath: '/package/$id/take'
      preLoaderRoute: typeof PackageIdTakeRouteImport
      parentRoute: typeof PackageIdRoute
    }
    '/package/$id/attempt/$attemptId': {
      id: '/package/$id/attempt/$attemptId'
      path: '/attempt/$attemptId'
      fullPath: '/package/$id/attempt/$attemptId'
      preLoaderRoute: typeof PackageIdAttemptAttemptIdRouteImport
      parentRoute: typeof PackageIdRoute
    }
  }
}

interface PackageIdRouteChildren {
  PackageIdTakeRoute: typeof PackageIdTakeRoute
  PackageIdIndexRoute: typeof PackageIdIndexRoute
  PackageIdAttemptAttemptIdRoute: typeof PackageIdAttemptAttemptIdRoute
}

const PackageIdRouteChildren: PackageIdRouteChildren = {
  PackageIdTakeRoute: PackageIdTakeRoute,
  PackageIdIndexRoute: PackageIdIndexRoute,
  PackageIdAttemptAttemptIdRoute: PackageIdAttemptAttemptIdRoute,
}

const PackageIdRouteWithChildren = PackageIdRoute._addFileChildren(
  PackageIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  BankRoute: BankRoute,
  GenerateRoute: GenerateRoute,
  HistoryRoute: HistoryRoute,
  JobsRoute: JobsRoute,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  MeRoute: MeRoute,
  PackagesRoute: PackagesRoute,
  SettingsRoute: SettingsRoute,
  AttemptIdRoute: AttemptIdRoute,
  PackageIdRoute: PackageIdRouteWithChildren,
  ProfileUserIdRoute: ProfileUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
