/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PackagesRouteImport } from './routes/packages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as GenerateRouteImport } from './routes/generate'
import { Route as BankRouteImport } from './routes/bank'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PackageIdRouteImport } from './routes/package.$id'
import { Route as BuilderComboRouteImport } from './routes/builder.combo'
import { Route as AttemptIdRouteImport } from './routes/attempt.$id'
import { Route as PackageIdIndexRouteImport } from './routes/package.$id.index'
import { Route as PackageIdTakeRouteImport } from './routes/package.$id.take'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PackagesRoute = PackagesRouteImport.update({
  id: '/packages',
  path: '/packages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const GenerateRoute = GenerateRouteImport.update({
  id: '/generate',
  path: '/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const BankRoute = BankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PackageIdRoute = PackageIdRouteImport.update({
  id: '/package/$id',
  path: '/package/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderComboRoute = BuilderComboRouteImport.update({
  id: '/builder/combo',
  path: '/builder/combo',
  getParentRoute: () => rootRouteImport,
} as any)
const AttemptIdRoute = AttemptIdRouteImport.update({
  id: '/attempt/$id',
  path: '/attempt/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PackageIdIndexRoute = PackageIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PackageIdRoute,
} as any)
const PackageIdTakeRoute = PackageIdTakeRouteImport.update({
  id: '/take',
  path: '/take',
  getParentRoute: () => PackageIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/bank': typeof BankRoute
  '/generate': typeof GenerateRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/packages': typeof PackagesRoute
  '/settings': typeof SettingsRoute
  '/attempt/$id': typeof AttemptIdRoute
  '/builder/combo': typeof BuilderComboRoute
  '/package/$id': typeof PackageIdRouteWithChildren
  '/package/$id/take': typeof PackageIdTakeRoute
  '/package/$id/': typeof PackageIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/bank': typeof BankRoute
  '/generate': typeof GenerateRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/packages': typeof PackagesRoute
  '/settings': typeof SettingsRoute
  '/attempt/$id': typeof AttemptIdRoute
  '/builder/combo': typeof BuilderComboRoute
  '/package/$id/take': typeof PackageIdTakeRoute
  '/package/$id': typeof PackageIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/bank': typeof BankRoute
  '/generate': typeof GenerateRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/packages': typeof PackagesRoute
  '/settings': typeof SettingsRoute
  '/attempt/$id': typeof AttemptIdRoute
  '/builder/combo': typeof BuilderComboRoute
  '/package/$id': typeof PackageIdRouteWithChildren
  '/package/$id/take': typeof PackageIdTakeRoute
  '/package/$id/': typeof PackageIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/bank'
    | '/generate'
    | '/jobs'
    | '/login'
    | '/packages'
    | '/settings'
    | '/attempt/$id'
    | '/builder/combo'
    | '/package/$id'
    | '/package/$id/take'
    | '/package/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/bank'
    | '/generate'
    | '/jobs'
    | '/login'
    | '/packages'
    | '/settings'
    | '/attempt/$id'
    | '/builder/combo'
    | '/package/$id/take'
    | '/package/$id'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/bank'
    | '/generate'
    | '/jobs'
    | '/login'
    | '/packages'
    | '/settings'
    | '/attempt/$id'
    | '/builder/combo'
    | '/package/$id'
    | '/package/$id/take'
    | '/package/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BankRoute: typeof BankRoute
  GenerateRoute: typeof GenerateRoute
  JobsRoute: typeof JobsRoute
  LoginRoute: typeof LoginRoute
  PackagesRoute: typeof PackagesRoute
  SettingsRoute: typeof SettingsRoute
  AttemptIdRoute: typeof AttemptIdRoute
  BuilderComboRoute: typeof BuilderComboRoute
  PackageIdRoute: typeof PackageIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/packages': {
      id: '/packages'
      path: '/packages'
      fullPath: '/packages'
      preLoaderRoute: typeof PackagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generate': {
      id: '/generate'
      path: '/generate'
      fullPath: '/generate'
      preLoaderRoute: typeof GenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank': {
      id: '/bank'
      path: '/bank'
      fullPath: '/bank'
      preLoaderRoute: typeof BankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/package/$id': {
      id: '/package/$id'
      path: '/package/$id'
      fullPath: '/package/$id'
      preLoaderRoute: typeof PackageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/combo': {
      id: '/builder/combo'
      path: '/builder/combo'
      fullPath: '/builder/combo'
      preLoaderRoute: typeof BuilderComboRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attempt/$id': {
      id: '/attempt/$id'
      path: '/attempt/$id'
      fullPath: '/attempt/$id'
      preLoaderRoute: typeof AttemptIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/package/$id/': {
      id: '/package/$id/'
      path: '/'
      fullPath: '/package/$id/'
      preLoaderRoute: typeof PackageIdIndexRouteImport
      parentRoute: typeof PackageIdRoute
    }
    '/package/$id/take': {
      id: '/package/$id/take'
      path: '/take'
      fullPath: '/package/$id/take'
      preLoaderRoute: typeof PackageIdTakeRouteImport
      parentRoute: typeof PackageIdRoute
    }
  }
}

interface PackageIdRouteChildren {
  PackageIdTakeRoute: typeof PackageIdTakeRoute
  PackageIdIndexRoute: typeof PackageIdIndexRoute
}

const PackageIdRouteChildren: PackageIdRouteChildren = {
  PackageIdTakeRoute: PackageIdTakeRoute,
  PackageIdIndexRoute: PackageIdIndexRoute,
}

const PackageIdRouteWithChildren = PackageIdRoute._addFileChildren(
  PackageIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  BankRoute: BankRoute,
  GenerateRoute: GenerateRoute,
  JobsRoute: JobsRoute,
  LoginRoute: LoginRoute,
  PackagesRoute: PackagesRoute,
  SettingsRoute: SettingsRoute,
  AttemptIdRoute: AttemptIdRoute,
  BuilderComboRoute: BuilderComboRoute,
  PackageIdRoute: PackageIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
